### ISSUE TITLE
Footer is not present in this website

### ISSUE THREAD

**Issue by rko0211** [AyishikD/disney-plus-clone#1]
Kindly review the issue and please assign me this task under apertre24. I want to contribute in this issue. Thank you.

**Comment by AyishikD** [comment]
> Kindly review the issue and please assign me this task under apertre24. I want to contribute in this issue. Thank you.

Can you show it?

**Comment by rko0211** [comment]
![Screenshot from 2024-01-03 14-39-49](https://github.com/AyishikD/disney-plus-clone/assets/97402824/64f54367-f9bd-462b-89b2-1039cb393312)

**Comment by AyishikD** [comment]
> ![Screenshot from 2024-01-03 14-39-49](https://private-user-images.githubusercontent.com/97402824/293872892-64f54367-f9bd-462b-89b2-1039cb393312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNzQ5ODksIm5iZiI6MTcwNDI3NDY4OSwicGF0aCI6Ii85NzQwMjgyNC8yOTM4NzI4OTItNjRmNTQzNjctZjliZC00NjJiLTg5YjItMTAzOWNiMzkzMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDA5MzgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOTk1OTFmODE4ODA3MzkzYjYyZGNmMmMxN2Y1NjU3MDkzNjhiMDVmYWNmNDQ2NjI5MGExNjE3YWZkZWJhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FWSWVFB8108m6pqJxuaprOQoREs3Y5JP2ZX-zYssNZw)

Medium tasks have 2 days validity 
Best of luck

**Comment by rko0211** [comment]
Thank you. I will do my best
