### ISSUE TITLE
The navitems were no visible 

### ISSUE THREAD

**Issue by Rick-03** [AyishikD/disney-plus-clone#18]
### Describe your issue

in the navbar section the nav items (search,home etc) are not visible and when open a particular component the hotstar icon is  not visible

### Steps to reproduce

1.go to navbar.js 
2.some changes in the tailwind css 

### What was the expected result?

the nav items is now visible with the hotstar logo
<img width="901" alt="image" src="https://github.com/AyishikD/disney-plus-clone/assets/116449504/0e24d5a9-0117-43ca-a15e-ac80e8b5bbad">

### Put here any screenshots or videos (optional)

here the navitems were not visible and also the logo

<img width="904" alt="Screenshot 2024-01-10 171227" src="https://github.com/AyishikD/disney-plus-clone/assets/116449504/eb50ee82-7216-4070-a649-797628eb635c">

### Would you like to work on this issue?

yes

**Comment by Rick-03** [comment]
Assign me under Aperture'24

**Comment by AyishikD** [comment]
@Rick-03 best of luck
