### ISSUE TITLE
Scroll Alignment Issue with Navbar Overlapping Content

### ISSUE THREAD

**Issue by Soumojitshome2023** [AyishikD/disney-plus-clone#19]
## Problem:
When scrolling down on the website, the content items start to overlap with the top of the navigation bar, causing a visual discrepancy.

## Expected Behavior:
The navigation bar should remain fixed at the top, and content items should scroll smoothly beneath it without any overlapping.

### Steps to reproduce

1. Open the website.
2. Scroll down the page.

### What was the expected result?

The navigation bar should remain fixed at the top, and content items should scroll smoothly beneath it without any overlapping.

### Put here any screenshots or videos (optional)

![Screenshot (473)](https://github.com/AyishikD/disney-plus-clone/assets/121761154/f9231539-2fe5-4fe7-8ed0-93fc40501e46)

### Would you like to work on this issue?

Yes

**Comment by Soumojitshome2023** [comment]
**Please assist me this issue, I want to work on it. :)**

**Comment by AyishikD** [comment]
@Soumojitshome2023 best of luck
