### ISSUE TITLE
Improve Responsiveness on Disney Plus Clone Website

### ISSUE THREAD

**Issue by Soumojitshome2023** [AyishikD/disney-plus-clone#24]
### Describe your issue

The Disney Plus clone website issues with responsiveness, particularly on various devices and screen sizes.

### Steps to reproduce

1. Access the Disney Plus clone website on a mobile device, tablet, and desktop.
2. Observe the layout and behavior on each device.

### What was the expected result?

The website should be responsive, providing a seamless user experience across different devices, including desktops, tablets, and mobile phones.

### Put here any screenshots or videos (optional)

![image](https://github.com/AyishikD/disney-plus-clone/assets/121761154/a3648fd1-b473-4070-8091-0c31d5caa078)

### Would you like to work on this issue?

Yes

**Comment by Soumojitshome2023** [comment]
Please assign me this issue. I want to work on it.

**Comment by AyishikD** [comment]
Best of luck @Soumojitshome2023
