### ISSUE TITLE
adding a better carousel effect

### ISSUE THREAD

**Issue by YooAshu** [AyishikD/disney-plus-clone#3]

**Comment by AyishikD** [comment]
> _No description provided._

Can u show?

**Comment by biswarup-naha** [comment]
I can take on this issue. If assigned I can work it up with a beautiful smooth horizontal scrolling effect with a timer for each.

**Comment by AyishikD** [comment]
> I can take on this issue. If assigned I can work it up with a beautiful smooth horizontal scrolling effect with a timer for each.

Best of luck and complete within 2 days
