### ISSUE TITLE
New Enhancement : Add some cool badges in README.md

### ISSUE THREAD

**Issue by apu52** [AyishikD/disney-plus-clone#35]
### Describe the feature

Hello Sir,
I want to add some cool badges in this repo like
- open issues
- contributor
- open PR
- last commites
this type of cool API badges

### It should be implemented because

It will be very helpful to showcase the stats of your Repo as well as will attract more contributors.

**Demo** 
![image](https://github.com/AyishikD/disney-plus-clone/assets/114172928/242d4042-664d-43cd-b30f-b79227fa8412)

### Additional context

Sir please assign me this issue under APERTRE'24

### Would you like to work on this issue?

yes

**Comment by apu52** [comment]
@AyishikD Please assign me this issue under APERTRE'24 . So that I can work on this issue.

**Comment by AyishikD** [comment]
Find good issue @apu52

**Comment by apu52** [comment]
> Find good issue @apu52

@AyishikD Shall I close this issue or can I work on this issue?

**Comment by AyishikD** [comment]
> > Find good issue @apu52
> 
> @AyishikD Shall I close this issue or can I work on this issue?

Close it
