### ISSUE TITLE
Creating the CONTRIBUTION.md file

### ISSUE THREAD

**Issue by trishit78** [AyishikD/disney-plus-clone#4]

**Comment by AyishikD** [comment]
> _No description provided._

Can you add a issue template?

**Comment by trishit78** [comment]
Yes I can

**Comment by AyishikD** [comment]
> Yes I can

Fine tomorrow i will assign

**Comment by AyishikD** [comment]
@trishit78 along with bug report can you add for "Add a new Feature"

**Comment by AyishikD** [comment]
Good work @trishit78
