### ISSUE TITLE
Adding: Hover Effect

### ISSUE THREAD

**Issue by abhraneel2004** [AyishikD/disney-plus-clone#40]
### Describe the feature

Adding hover effect on play and trailer button in details page

### It should be implemented because

it will make the details page interesting.

### Would you like to work on this issue?

Yes

**Comment by AyishikD** [comment]
Best of luck @abhraneel2004

**Comment by abhraneel2004** [comment]
Hello, I came here by searching html,css,js project. but I don't know react or tailwind, I am sorry but I cant contribute to this issue
